### ISSUE TITLE
Tracking: configuration cleanup

### ISSUE THREAD

**Issue by madnificent** [lblod/app-contact-hub#44]
Whilst reviewing #30 some issues popped up.  If any of these are fixed, it is smart to base them off of refactor/docker-compose-configs or master once the PR has been merged.

- [x] Consistently add logging statements
- [x] We should hunt (me?) to ensure we have tagged (or at least feature-based) releases everywhere
- [x] Move checking of access rights from web into Kalliope service
- [x] Remove unused configuration files

**Comment by Windvis** [comment]
It seems everything was resolved so I'm closing the issue. Feel free to reopen if there are more things to do.
